controller:
  # Solo configuraciones que no están en el ConfigMap existente
  config:
    http-snippet: |
      map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
      }
