controller:
  # Solo configuraciones que no están en el ConfigMap existente
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

  # Snippet adicional que no está en el ConfigMap
  config:
    http-snippet: |
      map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
      }
