# Configuración personalizada de Prometheus
server:
  global:
    evaluation_interval: 15s

  persistentVolume:
    size: 8Gi
    storageClass: ""

  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

  # Habilitar soporta para ServiceMonitor CRD
  serviceMonitorSelector:
    matchLabels:
      release: prometheus

# Recolector de métricas de nodes
nodeExporter:
  enabled: true

# Métricas del cluster Kubernetes
kubeStateMetrics:
  enabled: true

# Reglas de alerta básicas
serverFiles:
  alerting_rules.yml:
    groups:
      - name: kubernetes-apps
        rules:
          - alert: PodNotRunning
            expr: kube_pod_status_phase{phase=~"Pending|Unknown|Failed"} > 0
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: Pod {{ $labels.namespace }}/{{ $labels.pod }} not running
              description: Pod {{ $labels.namespace }}/{{ $labels.pod }} has been in a non-running state for more than 5 minutes.

          - alert: HighCPUUsage
            expr: sum(rate(container_cpu_usage_seconds_total{namespace!="kube-system"}[5m])) by (pod) > 0.8
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: High CPU usage for {{ $labels.pod }}
              description: Pod {{ $labels.pod }} CPU usage exceeds 80% for more than 5 minutes.

          - alert: HighMemoryUsage
            expr: sum(container_memory_usage_bytes{namespace!="kube-system"}) by (pod) / sum(container_spec_memory_limit_bytes{namespace!="kube-system"}) by (pod) > 0.8
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: High memory usage for {{ $labels.pod }}
              description: Pod {{ $labels.pod }} memory usage exceeds 80% for more than 5 minutes.
